Added a bunch of scripts for creating CAs and getting node keys signed. Trust store has been rolled into the individual nodes' key stores. Note that this has resulted in a change in the fab-store script's options.

diff --git a/bin/genkey b/bin/genkey
--- a/bin/genkey
+++ b/bin/genkey
@@ -1,25 +1,200 @@
 #!/bin/bash
 
-source "$(dirname $0)/defs"
+# Creates a key pair and certificate-signing request for a Fabric node.
 
-if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]] ; then
-  echo "Generates SSL keys and certificates for a store or worker"
-  echo "and adds them to the common trust store. Note you can"
-  echo "mention more than one host at a time."
-  echo 
-  echo "Usage: $(basename $0) <store hostname | worker name> ..."
-  echo
-  echo "  e.g. $(basename $0) store0 worker1 store2 store3 worker4"
+source "$(dirname "$0")/defs"
+
+DEFAULT_KEYSIZE=2048
+
+function usage() {
+  cat >&2 <<EOF
+Usage: $(basename "$0") [options]
+
+  Creates a key pair and certificate-signing request for a Fabric node.
+
+Options:
+  --hostname name
+      the DNS hostname of the node for which the key pair is to be made.
+      Default: ${HOSTNAME:-\$HOSTNAME}
+
+  --keysize bits
+      the length of the node's private key. Default: ${DEFAULT_KEYSIZE}
+
+  --keystore filename
+      the keystore to which the new key pair is to be added. The keystore will
+      be created if it does not exist.
+      Default: ${TOP}/etc/keys/HOSTNAME.keystore
+
+  --pass password
+      the password for the keystore. This must be at least six characters long.
+      If this is not provided on the command line, the user will be prompted
+      for the password.
+
+  --csr filename
+      the filename to which the certificate-signing request will be written.
+      Default: ${TOP}/etc/csr/HOSTNAME.csr
+
+  The following are optional. If not specified, they will be left blank.
+
+  --c country
+      the C component of the node's Distinguished Name. This is usually your
+      country's two-letter code.
+
+  --st state_or_province
+      the ST component of the node's Distinguished Name. This is usually the
+      full name of your state or province.
+
+  --l locality_or_city
+      the L component of the node's Distinguished Name. This is usually the
+      name of your city.
+
+  --o organization
+      the O component of the node's Distinguised Name. This is usually the name
+      of your organization or company.
+
+  --ou organizational_unit_name
+      the OU component of the node's Distinguished Name. This is usually the
+      name of your organizational unit within your organization or company.
+EOF
   exit 1
+}
+
+function error() {
+  echo "$(basename "$0")": "$@" >&2
+  echo "Try \`$(basename "$0") --help' for more information" >&2
+  exit 1
+}
+
+function noArg() {
+  error "Missing argument to --$1 option."
+}
+
+KEYSIZE="${DEFAULT_KEYSIZE}"
+
+while true; do
+  case "$1" in
+    "") break ;;
+    --hostname)
+      shift
+      HOSTNAME="$1"
+      shift || noArg hostname
+      ;;
+    --keysize)
+      shift
+      KEYSIZE="$1"
+      shift || noArg keysize
+      ;;
+    --keystore)
+      shift
+      KEYSTORE="$1"
+      shift || noArg keystore
+      ;;
+    --pass)
+      shift
+      PASSWD="$1"
+      shift || noArg pass
+      ;;
+    --csr)
+      shift
+      CSR="$1"
+      shift || noArg csr
+      ;;
+    --c)
+      shift
+      C="$1"
+      shift || noArg c
+      ;;
+    --st)
+      shift
+      ST="$1"
+      shift || noArg st
+      ;;
+    --l)
+      shift
+      L="$1"
+      shift || noArg l
+      ;;
+    --o)
+      shift
+      O="$1"
+      shift || noArg o
+      ;;
+    --ou)
+      shift
+      OU="$1"
+      shift || noArg ou
+      ;;
+    -h|--help|-\?)
+      usage
+      ;;
+    -*)
+      error "Invalid option: $1"
+      ;;
+    *)
+      error "Invalid argument: $1"
+  esac
+done
+
+[[ -z "${HOSTNAME}" ]] && error Must specify a hostname.
+
+# Assign default values to unspecified options.
+[[ -z "${KEYSTORE}" ]] && KEYSTORE="${TOP}/etc/keys/${HOSTNAME}.keystore"
+
+if [[ -z "${CSR}" ]] ; then
+  CSR="${TOP}/etc/csr/${HOSTNAME}.csr"
+  mkdir -p "${TOP}/etc/csr"
 fi
 
-DIR="${TOP}/etc/keys"
+# Construct the DN.
+DN="CN=${HOSTNAME}"
+[[ -n "${OU}" ]] && DN="${DN}, OU=${OU}"
+[[ -n "${O}" ]] && DN="${DN}, O=${O}"
+[[ -n "${L}" ]] && DN="${DN}, L=${L}"
+[[ -n "${ST}" ]] && DN="${DN}, ST=${ST}"
+[[ -n "${C}" ]] && DN="${DN}, C=${C}"
 
-for i in "$@" ; do
-  keytool -genkey -alias "$i" -keyalg rsa -keysize 1024 -dname "CN="$i", OU=Fabric, O=Cornell University, L=Ithaca, ST=NY, C=US" -keypass 'password' -keystore "$(fixfilename ${DIR}/"$i".keystore)" -storepass 'password'
-  keytool -export -alias "$i" -keystore "$(fixfilename ${DIR}/"$i".keystore)" -keypass 'password' -file "$(fixfilename ${DIR}/"$i".cert)" -storepass 'password'
+# If necessary, ask for the keystore password.
+while [[ -z "${PASSWD}" ]] ; do
+  while true ; do
+    echo -n "Enter keystore password: "
+    stty -echo
+    read -r PASSWD
+    stty echo
+    echo
 
-  keytool -import -noprompt -alias "$i" -keystore "$(fixfilename ${DIR}/trust.keystore)" -file "$(fixfilename ${DIR}/"$i".cert)" -storepass 'password'
-  rm "${DIR}/$i".cert
+    [[ $(echo -n "${PASSWD}" | wc -c) -ge 6 ]] && break
+    echo Keystore password is too short - must be at least 6 characters
+  done
+
+  if [[ ! -f "${KEYSTORE}" ]] ; then
+    # Creating a new keystore. Verify the password.
+    echo -n "Verify new keystore password: "
+    stty -echo
+    read -r PASSWD_CONFIRM
+    stty echo
+    echo
+
+    if [[ "${PASSWD}" != "${PASSWD_CONFIRM}" ]] ; then
+      echo "Passwords do not match."
+      PASSWD=
+    fi
+  fi
+
+  echo
 done
+
+# Generate the key pair.
+keytool -genkeypair -alias "${HOSTNAME}" -keyalg rsa -keysize "${KEYSIZE}" \
+  -keypass "${PASSWD}" -dname "${DN}" -keystore "${KEYSTORE}" \
+  -storepass "${PASSWD}" || exit 1
+
+# Generate the CSR.
+keytool -certreq -alias "${HOSTNAME}" -file "${CSR}" -keystore "${KEYSTORE}" \
+  -storepass "${PASSWD}" || exit 1
+
+cat <<EOF
+CSR saved in ${CSR}
+
+Copy this file to your CA and run the \`ca-sign' script there.
+EOF
 
